apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jenkins-secrets
  namespace: jenkins-master
spec:
  provider: aws
  secretObjects:
  - secretName: jenkins-secrets
    type: Opaque
    data:
    - objectName: build_useralias
      key: build_username
    - objectName: build_passalias
      key: build_password 
    - objectName: admin_useralias
      key: admin_username 
    - objectName: admin_passalias
      key: admin_password 
    - objectName: read_useralias
      key: read_username
    - objectName: read_passalias
      key: read_password
  parameters:
    objects: |
      - objectName: "jenkins"
        objectType: "secretsmanager"
        jmesPath:
          - path: build_user
            objectAlias: build_useralias
          - path: build_pass
            objectAlias: build_passalias
          - path: admin_user
            objectAlias: admin_useralias
          - path: admin_pass
            objectAlias: admin_passalias
          - path: read_user
            objectAlias: read_useralias
          - path: read_pass
            objectAlias: read_passalias
---
